# dark pattern classes
class_dp = {
    "activity_message": "activity_message"
    , "high_demand_message": "high_demand_message"
    , "low_stock_message": "low_stock_message"
    , "limited_time_message": "limited_time_message"
    , "countdown_timer": "countdown_timer"
    # , "false_hierarchy": "false_hierarchy"
    , "attention_distraction": "attention_distraction"
    , "default_choice": "default_choice"
    , "friend_spam": "friend_spam"
    , "forced_enrollment": "forced_enrollment"
    , "disguised_ads": "disguised_ads"
    , "social_pyramid": "social_pyramid"
    , "privacy_zuckering": "privacy_zuckering"
    , "intermediate_currency": "intermediate_currency"
    , "price_comparison_prevention": "price_comparison_prevention"
    , "nagging": "nagging"
    # , "bait_and_switch": "bait_and_switch"
    , "gamification": "gamification"
    , "roach_motel": "roach_motel"
    , "forced_continuity": "forced_continuity"
}
