# dark pattern classes
class_dp = {
    "activity_message": "ACTIVITY MESSAGE"
    , "high_demand_message": "HIGH DEMAND MESSAGE"
    , "low_stock_message": "LOW STOCK MESSAGE"
    , "limited_time_message": "LIMITED TIME MESSAGE"
    , "countdown_timer": "COUNTDOWN TIMER"
    # , "false_hierarchy": "FALSE HIERARCHY"
    , "attention_distraction": "ATTENTION DISTRACTION"
    , "default_choice": "DEFAULT CHOICE"
    , "friend_spam": "FRIEND SPAM"
    , "forced_enrollment": "FORCED ENROLLMENT"
    , "disguised_ads": "DISGUISED ADS"
    , "social_pyramid": "SOCIAL PYRAMID"
    , "privacy_zuckering": "PRIVACY ZUCKERING"
    , "intermediate_currency": "INTERMEDIATE CURRENCY"
    , "price_comparison_prevention": "PRICE COMPARISON PREVENTION"
    , "nagging": "NAGGING"
    # , "bait_and_switch": "BAIT AND SWITCH"
    , "gamification": "GAMIFICATION"
    , "roach_motel": "ROACH MOTEL"
    , "forced_continuity": "FORCED CONTINUITY"
}
